<?php

// raw ingredients used by seeders.php to build fake demo data.
// no database code here at all - just plain arrays to pick from.

$adjectives = ["Quiet", "Salty", "Drifting", "Hidden", "Lonely", "Restless", "Faded", "Gentle", "Weary", "Distant"];
$nouns = ["Harbor", "Wave", "Compass", "Tide", "Shore", "Anchor", "Current", "Horizon", "Lighthouse", "Reef"];

// each bottle owns its own marks, so the marks actually relate to what
// the bottle says - some bottles have none, some have a few
$bottles = [
    ["content" => "I told everyone I got the internship. I didn't.", "marks" => ["i've been there, it's rough", "your secret's safe with the ocean"]],
    ["content" => "I still eat cereal for dinner more nights than I'd like to admit.", "marks" => ["honestly a solid meal choice", "no judgment here, cereal is underrated"]],
    ["content" => "I've rewatched the same show four times because starting something new feels like too much effort.", "marks" => ["comfort over novelty, always"]],
    ["content" => "I said 'you too' when the waiter told me to enjoy my meal.", "marks" => ["we've all done this", "the wave of regret is real"]],
    ["content" => "I laughed at the joke but I didn't get it.", "marks" => []],
    ["content" => "I have 47 unread emails and I've made peace with it.", "marks" => ["47 is rookie numbers honestly", "the peace is the real achievement"]],
    ["content" => "I practiced the apology in the mirror and never actually sent it.", "marks" => ["send it, i promise it helps"]],
    ["content" => "I still remember my childhood best friend's phone number but not my own.", "marks" => ["some numbers just stick", "you should call it sometime"]],
    ["content" => "I told my group chat I was 'so busy' and then took a three hour nap.", "marks" => ["the most productive lie"]],
    ["content" => "I cried at a car commercial last week. A CAR commercial.", "marks" => ["they're getting really good at those"]],
    ["content" => "I finally fixed the thing that's been broken for six months and I feel unstoppable.", "marks" => ["that feeling is unmatched", "what was it, i need the same high"]],
    ["content" => "I talk to my plants and I'm convinced one of them talks back.", "marks" => ["which one, i need to know"]],
    ["content" => "I got the job I actually wanted and I still can't believe it.", "marks" => ["congratulations, genuinely", "you earned this"]],
    ["content" => "I pretend I know what's happening in meetings by nodding a lot.", "marks" => ["the universal survival skill"]],
    ["content" => "I danced alone in my kitchen tonight and it was the best part of my week.", "marks" => ["this is the whole point of kitchens"]],
    ["content" => "I've had the same 'I'll start tomorrow' plan for two years now.", "marks" => []],
    ["content" => "I deleted the app three times and reinstalled it three times.", "marks" => ["the loop we all know", "at least you're consistent"]],
    ["content" => "I wore mismatched socks to an interview and got the job anyway.", "marks" => ["clearly the socks were a good luck charm"]],
    ["content" => "I said yes to something I didn't want to do just to avoid an awkward silence.", "marks" => ["it's okay to just say no next time"]],
    ["content" => "I finally said the hard thing out loud and nothing bad happened.", "marks" => ["that takes real courage", "i needed to hear this today"]],
    ["content" => "I'm proud of myself today and I don't say that enough.", "marks" => ["say it more often, you deserve it", "proud of you too"]],
    ["content" => "I once returned to a store three times because I was too nervous to ask a question.", "marks" => ["the customer service anxiety is real"]],
    ["content" => "I still have a voicemail I can't bring myself to delete.", "marks" => ["that's okay, keep it as long as you need"]],
    ["content" => "I made a five year plan and immediately fell asleep thinking about it.", "marks" => []],
    ["content" => "I gave a stranger my umbrella and thought about it happily for the rest of the day.", "marks" => ["small kindnesses stick with you", "this made my day just reading it"]],
    ["content" => "I still have the tag on a shirt I bought eight months ago.", "marks" => ["wear it or return it, no in between"]],
    ["content" => "I told my roommate I was asleep so I didn't have to talk.", "marks" => ["introvert survival tactics", "we've all faked it at some point"]],
    ["content" => "I clapped when the plane landed and nobody else did.", "marks" => ["someone has to start the tradition"]],
    ["content" => "I've had a plant on my desk for a year and I still don't know what kind it is.", "marks" => ["it's thriving under mystery care"]],
    ["content" => "I called in sick to finish a book I couldn't put down.", "marks" => ["worth it if the book was good", "no shame, the book always wins"]],
    ["content" => "I practiced my order out loud before walking into the coffee shop.", "marks" => ["we've all rehearsed a coffee order"]],
    ["content" => "I finally paid off my credit card and did a little dance about it.", "marks" => ["that dance was earned", "financial wins deserve a celebration"]],
    ["content" => "I still think about a comment someone made about my hair three years ago.", "marks" => ["it lives rent free, i understand completely"]],
    ["content" => "I pretended to know a shortcut and got us both lost for twenty minutes.", "marks" => ["confidence over accuracy, i respect it"]],
    ["content" => "I read the last page of the book first because I couldn't handle the suspense.", "marks" => ["valid strategy honestly"]],
    ["content" => "I stayed up too late finishing a project and it turned out better than anything I've made rushing.", "marks" => ["sometimes the pressure works in our favor"]],
    ["content" => "I told a coworker I loved their idea in the meeting when I completely zoned out.", "marks" => ["classic meeting survival", "we've all nodded through a zone-out"]],
    ["content" => "I've kept a plant alive for six months and consider it a major life achievement.", "marks" => ["it is one, don't let anyone tell you otherwise"]],
    ["content" => "I waved back at someone who wasn't waving at me.", "marks" => ["the wave commitment is the hardest part", "we've all had to play it off"]],
    ["content" => "I finally called my grandmother back and we talked for two hours.", "marks" => ["this made me want to call mine too"]],
    ["content" => "I pretended not to see my ex at the grocery store and hid in the cereal aisle.", "marks" => ["the cereal aisle is a safe haven"]],
    ["content" => "I wrote a to-do list just to have the satisfaction of crossing something off immediately.", "marks" => ["the dopamine hit is real", "no shame, it works"]],
    ["content" => "I laughed so hard at something dumb that I cried in public.", "marks" => ["those are the best kind of laughs"]],
    ["content" => "I still remember exactly what song was playing during a good memory from years ago.", "marks" => ["music really holds onto things for us", "which song, i'm curious now"]],
    ["content" => "I complimented a stranger's outfit and made both our days better.", "marks" => ["this is exactly the kind of thing the world needs more of"]],
    ["content" => "I finally organized my closet and found three things I forgot I owned.", "marks" => ["closet archaeology is always a surprise"]],
    ["content" => "I've had the same ringtone since 2014 and I refuse to change it.", "marks" => ["some things shouldn't change, honestly", "at least you always know it's your phone"]],
    ["content" => "I remembered an embarrassing thing I did in middle school at 2am for no reason.", "marks" => ["the 2am memory ambush is brutal"]],
    ["content" => "I finally tried the recipe I bookmarked a year ago and it actually turned out great.", "marks" => ["a year is basically right on schedule", "so proud of past you for bookmarking it"]],
    ["content" => "I let myself rest today without feeling guilty about it and it felt like a small victory.", "marks" => ["rest is productive too, good for you"]],
    ["content" => "I still flinch a little every time my phone rings unexpectedly.", "marks" => ["caller id ruined phone calls for everyone", "same, unknown numbers are a whole event", "answering unprepared should be an olympic sport"]],
    ["content" => "I finally beat the level I'd been stuck on for a week and yelled loud enough to scare the cat.", "marks" => ["the cat forgives you eventually", "that victory was earned", "worth every bit of the noise"]],
    ["content" => "I told the barista my name wrong just to see what they'd write on the cup.", "marks" => ["chaotic but valid", "i need to see what they wrote", "this is a bit i respect"]],
    ["content" => "I've had a half-finished puzzle on my table for three weeks and I walk past it like it's furniture.", "marks" => ["it's decor now, accept it", "puzzles are a long term commitment", "no rush, it'll get there"]],
    ["content" => "I said 'happy birthday' to a coworker whose birthday was actually next month.", "marks" => ["the sentiment still counts", "early well wishes are still well wishes", "hope they were kind about it"]],
    ["content" => "I finally learned how to parallel park properly and I've told everyone I know.", "marks" => ["a milestone worth announcing honestly", "genuinely underrated skill", "proud of you, seriously"]],
    ["content" => "I keep a running list of words I like the sound of and no real reason for it.", "marks" => ["this is such a nice thing to collect", "i want to see the list", "words deserve appreciation too"]],
    ["content" => "I pretended to be on a call to avoid a conversation in the elevator.", "marks" => ["the elevator is a battlefield", "we've all needed this escape route", "no shame, survival instincts"]],
    ["content" => "I finally understood a joke from months ago and laughed out loud alone in my room.", "marks" => ["delayed laughter is still laughter", "this happens to me constantly", "hope it was worth the wait"]],
    ["content" => "I've rearranged my furniture four times this year looking for a layout that feels right.", "marks" => ["the search continues, respect the process", "furniture feng shui is real", "let us know when you find it"]],
    ["content" => "I said 'I'm never doing that again' and then did it again a week later.", "marks" => ["a timeless personal tradition", "we've all broken this promise", "no judgment, it happens"]],
    ["content" => "I finally sent the email I'd been drafting for two weeks and immediately felt lighter.", "marks" => ["that relief is unmatched", "so glad you sent it", "the draft folder loses one more hostage"]],
    ["content" => "I still remember the exact smell of my grandparents' house even though it's been years.", "marks" => ["smell memories are the strongest ones", "this made me think of mine too", "that's a beautiful thing to still carry"]],
    ["content" => "I bought a plant specifically because I liked the pot and I'm not sorry about it.", "marks" => ["valid purchasing strategy", "the pot deserved it honestly", "no regrets is the right attitude"]],
    ["content" => "I practiced a hard conversation in the shower and somehow still froze when it actually happened.", "marks" => ["the shower version is always braver", "this happens to the best of us", "hope the real conversation went okay anyway"]],
    ["content" => "I've kept the same wallpaper on my phone for four years because changing it feels like too big a decision.", "marks" => ["some decisions deserve that much caution", "the wallpaper has earned tenure at this point", "i respect the commitment"]],
    ["content" => "I told a stranger they dropped something just so I'd have an excuse to talk to them.", "marks" => ["bold and resourceful honestly", "did it work", "this is secretly kind of sweet"]],
    ["content" => "I finally finished the book I'd restarted four times and cried at the ending.", "marks" => ["fourth time's the charm apparently", "good endings deserve real tears", "so glad you finally got there"]],
    ["content" => "I still can't throw away the birthday cards from people who aren't around anymore.", "marks" => ["you don't have to, ever", "those are worth keeping", "this really got me, sending you warmth"]]
];

?>
